### ISSUE TITLE
whats different compare to Hipaway-Travel/HipMandrillBundle ?

### ISSUE THREAD

**Issue by gondo** [hamaryuginh/HamaryuginhMandrillBundle#1]

**Comment by hamaryuginh** [comment]
Hipaway-Travel/HipMandrillBundle can only send message.
HamaryuginhMandrillBundle will manage the entire account mandrill (message, tag, template, etc...) and get the response as an object.

**Comment by gondo** [comment]
i see, thanks!
mb add this plan to main Readme file?
